# Generated by Django 4.2.7 on 2024-12-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "plan_site",
            "0002_role_status_remove_task_deadline_remove_task_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_plans",
                to="plan_site.user",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="plan_site.status",
            ),
        ),
    ]
