# Generated by Django 4.2.7 on 2024-12-06 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plan_site", "0003_report_updated_at_alter_plan_supervisor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="plan_site.user",
            ),
        ),
    ]
