# Generated by Django 4.2.7 on 2024-12-12 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plan_site", "0005_reportstatus_taskstatus_rename_status_planstatus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="plan_site.plan",
            ),
        ),
    ]
