# Generated by Django 4.2.7 on 2024-12-12 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plan_site", "0007_alter_report_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_plan",
                to="plan_site.planstatus",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_url",
                to="plan_site.plan",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="report_status",
                to="plan_site.reportstatus",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_status",
                to="plan_site.taskstatus",
            ),
        ),
    ]
