# Generated by Django 4.2.7 on 2024-12-12 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plan_site", "0008_alter_plan_status_alter_report_plan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plan_status",
                to="plan_site.planstatus",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_url",
                to="plan_site.plan",
            ),
        ),
    ]
